### ISSUE TITLE
Cant execute build.sh command

### ISSUE THREAD

**Issue by TheSg2** [BeChris100/osintgram4j#1]
Hello! Im having troubles with the build.sh, im in cloudshell and when I execute build.sh it says this : 

The major JDK Version needs to be at least on the JDK 20.
To obtain the newest JDK Version, run the setup.sh with the '--force-download' argument

So i did that but it keeps droping me the same message.

Any solutions?

**Comment by BeChris100** [comment]
The thing is that I made the project require at least Java 20. As the message suggests, you can run the script by passing this:

```
./setup.sh --force-download
./build.sh
```

However, I might think about the Java 11/17 Requirement.

**Comment by TheSg2** [comment]
yea no I get it but i run the code, and when it says that the setup proces has finished I get the exact same message, idk why maybe a problem with cloudshell?

**Comment by BeChris100** [comment]
What JDK are you running on?

**Comment by BeChris100** [comment]
I fixed up the Building Script, so I hope that it fixed the error. If not, then do you have a new error message in any case?

**Comment by TheSg2** [comment]
Thankk youu, let me check i was playing league lol

**Comment by TheSg2** [comment]
maybe im doing something wrong, but it says me the same :(

**Comment by BeChris100** [comment]
Try redownloading the repository by doing `git clone https://github.com/BeChris100/osintgram4j`, as I did new updates. Afterward, can you give me all the console logs that you get?

**Comment by TheSg2** [comment]
sure, thanks.

**Comment by TheSg2** [comment]
Did it again, same result. Do you want me to send you all the logs? Its pretty large 

>Cloning into 'osintgram4j'...
remote: Enumerating objects: 234, done.
remote: Counting objects: 100% (234/234), done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 234 (delta 61), reused 221 (delta 51), pack-reused 0
Receiving objects: 100% (234/234), 242.65 KiB | 5.27 MiB/s, done.
Resolving deltas: 100% (61/61), done.
thekintgamer@cloudshell:~$ cd osintgram4j/
thekintgamer@cloudshell:~/osintgram4j$ ./setip.sh
-bash: ./setip.sh: No such file or directory
thekintgamer@cloudshell:~/osintgram4j$ ./setup.sh
## Operating System State
Is Linux: true
Is OSX (macOS): false

Preparing files (JDK, Libraries)

JDK Tools have been found.
--2023-09-17 19:45:46--  https://repo1.maven.org/maven2/org/json/json/20230618/json-20230618.jar
Resolving repo1.maven.org (repo1.maven.org)... 199.232.192.209, 199.232.196.209, 2a04:4e42:4c::209, ...
Connecting to repo1.maven.org (repo1.maven.org)|199.232.192.209|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 73447 (72K) [application/java-archive]
Saving to: ‘build/libs/json.jar’

build/libs/json.jar                             100%[=======================================================================================================>]  71.73K  --.-KB/s    in 0.01s   

2023-09-17 19:45:46 (4.95 MB/s) - ‘build/libs/json.jar’ saved [73447/73447]

## Setup Process completed
To continue, run the Build Script to complete the build process.
thekintgamer@cloudshell:~/osintgram4j$ ./build.sh
You need at least the JDK version of 20. Reported Java Version is 17
To obtain the newest JDK Version, run the setup.sh with the '--force-download' argument.
thekintgamer@cloudshell:~/osintgram4j$ ./setup.sh --force-download
## Operating System State
Is Linux: true
Is OSX (macOS): false

Preparing files (JDK, Libraries)

--2023-09-17 19:46:19--  https://download.java.net/java/GA/jdk21/fd2272bbf8e04c3dbaee13770090416c/35/GPL/openjdk-21_linux-x64_bin.tar.gz
Resolving download.java.net (download.java.net)... 184.24.36.87
Connecting to download.java.net (download.java.net)|184.24.36.87|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 203348211 (194M) [application/x-gzip]
Saving to: ‘build/jdk/tmp/jdk21.tar.gz’

build/jdk/tmp/jdk21.tar.gz                      100%[=======================================================================================================>] 193.93M  99.1MB/s    in 2.0s    

2023-09-17 19:46:21 (99.1 MB/s) - ‘build/jdk/tmp/jdk21.tar.gz’ saved [203348211/203348211]

jdk-21/bin/jar
jdk-21/bin/jarsigner
jdk-21/bin/java
jdk-21/bin/javac
jdk-21/bin/javadoc
jdk-21/bin/javap
jdk-21/bin/jcmd
jdk-21/bin/jconsole
jdk-21/bin/jdb
jdk-21/bin/jdeprscan
jdk-21/bin/jdeps
jdk-21/bin/jfr
jdk-21/bin/jhsdb
jdk-21/bin/jimage
jdk-21/bin/jinfo
jdk-21/bin/jlink
jdk-21/bin/jmap
jdk-21/bin/jmod
jdk-21/bin/jpackage
jdk-21/bin/jps
jdk-21/bin/jrunscript
jdk-21/bin/jshell
jdk-21/bin/jstack
jdk-21/bin/jstat
jdk-21/bin/jstatd
jdk-21/bin/jwebserver
jdk-21/bin/keytool
jdk-21/bin/rmiregistry
jdk-21/bin/serialver
jdk-21/conf/jaxp.properties
jdk-21/conf/logging.properties
jdk-21/conf/management/jmxremote.access
jdk-21/conf/management/jmxremote.password.template
jdk-21/conf/management/management.properties
jdk-21/conf/net.properties
jdk-21/conf/sdp/sdp.conf.template
jdk-21/conf/security/java.policy
jdk-21/conf/security/java.security
jdk-21/conf/security/policy/README.txt
jdk-21/conf/security/policy/limited/default_US_export.policy
jdk-21/conf/security/policy/limited/default_local.policy
jdk-21/conf/security/policy/limited/exempt_local.policy
jdk-21/conf/security/policy/unlimited/default_US_export.policy
jdk-21/conf/security/policy/unlimited/default_local.policy
jdk-21/conf/sound.properties
jdk-21/include/classfile_constants.h
jdk-21/include/jawt.h
jdk-21/include/jdwpTransport.h
jdk-21/include/jni.h
jdk-21/include/jvmti.h
jdk-21/include/jvmticmlr.h
jdk-21/include/linux/jawt_md.h
jdk-21/include/linux/jni_md.h
jdk-21/jmods/java.base.jmod
jdk-21/jmods/java.compiler.jmod
jdk-21/jmods/java.datatransfer.jmod
jdk-21/jmods/java.desktop.jmod
jdk-21/jmods/java.instrument.jmod
jdk-21/jmods/java.logging.jmod
jdk-21/jmods/java.management.jmod
jdk-21/jmods/java.management.rmi.jmod
jdk-21/jmods/java.naming.jmod
jdk-21/jmods/java.net.http.jmod
jdk-21/jmods/java.prefs.jmod
jdk-21/jmods/java.rmi.jmod
jdk-21/jmods/java.scripting.jmod
jdk-21/jmods/java.se.jmod
jdk-21/jmods/java.security.jgss.jmod
jdk-21/jmods/java.security.sasl.jmod
jdk-21/jmods/java.smartcardio.jmod
jdk-21/jmods/java.sql.jmod
jdk-21/jmods/java.sql.rowset.jmod
jdk-21/jmods/java.transaction.xa.jmod
jdk-21/jmods/java.xml.crypto.jmod
jdk-21/jmods/java.xml.jmod
jdk-21/jmods/jdk.accessibility.jmod
jdk-21/jmods/jdk.attach.jmod
jdk-21/jmods/jdk.charsets.jmod
jdk-21/jmods/jdk.compiler.jmod
jdk-21/jmods/jdk.crypto.cryptoki.jmod
jdk-21/jmods/jdk.crypto.ec.jmod
jdk-21/jmods/jdk.dynalink.jmod
jdk-21/jmods/jdk.editpad.jmod
jdk-21/jmods/jdk.hotspot.agent.jmod
jdk-21/jmods/jdk.httpserver.jmod
jdk-21/jmods/jdk.incubator.vector.jmod
jdk-21/jmods/jdk.internal.ed.jmod
jdk-21/jmods/jdk.internal.jvmstat.jmod
jdk-21/jmods/jdk.internal.le.jmod
jdk-21/jmods/jdk.internal.opt.jmod
jdk-21/jmods/jdk.internal.vm.ci.jmod
jdk-21/jmods/jdk.internal.vm.compiler.jmod
jdk-21/jmods/jdk.internal.vm.compiler.management.jmod
jdk-21/jmods/jdk.jartool.jmod
jdk-21/jmods/jdk.javadoc.jmod
jdk-21/jmods/jdk.jcmd.jmod
jdk-21/jmods/jdk.jconsole.jmod
jdk-21/jmods/jdk.jdeps.jmod
jdk-21/jmods/jdk.jdi.jmod
jdk-21/jmods/jdk.jdwp.agent.jmod
jdk-21/jmods/jdk.jfr.jmod
jdk-21/jmods/jdk.jlink.jmod
jdk-21/jmods/jdk.jpackage.jmod
jdk-21/jmods/jdk.jshell.jmod
jdk-21/jmods/jdk.jsobject.jmod
jdk-21/jmods/jdk.jstatd.jmod
jdk-21/jmods/jdk.localedata.jmod
jdk-21/jmods/jdk.management.agent.jmod
jdk-21/jmods/jdk.management.jfr.jmod
jdk-21/jmods/jdk.management.jmod
jdk-21/jmods/jdk.naming.dns.jmod
jdk-21/jmods/jdk.naming.rmi.jmod
jdk-21/jmods/jdk.net.jmod
jdk-21/jmods/jdk.nio.mapmode.jmod
jdk-21/jmods/jdk.random.jmod
jdk-21/jmods/jdk.sctp.jmod
jdk-21/jmods/jdk.security.auth.jmod
jdk-21/jmods/jdk.security.jgss.jmod
jdk-21/jmods/jdk.unsupported.desktop.jmod
jdk-21/jmods/jdk.unsupported.jmod
jdk-21/jmods/jdk.xml.dom.jmod
jdk-21/jmods/jdk.zipfs.jmod
jdk-21/legal/java.base/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.base/ASSEMBLY_EXCEPTION
jdk-21/legal/java.base/LICENSE
jdk-21/legal/java.base/aes.md
jdk-21/legal/java.base/asm.md
jdk-21/legal/java.base/c-libutl.md
jdk-21/legal/java.base/cldr.md
jdk-21/legal/java.base/icu.md
jdk-21/legal/java.base/public_suffix.md
jdk-21/legal/java.base/unicode.md
jdk-21/legal/java.compiler/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.compiler/ASSEMBLY_EXCEPTION
jdk-21/legal/java.compiler/LICENSE
jdk-21/legal/java.datatransfer/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.datatransfer/ASSEMBLY_EXCEPTION
jdk-21/legal/java.datatransfer/LICENSE
jdk-21/legal/java.desktop/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.desktop/ASSEMBLY_EXCEPTION
jdk-21/legal/java.desktop/LICENSE
jdk-21/legal/java.desktop/colorimaging.md
jdk-21/legal/java.desktop/giflib.md
jdk-21/legal/java.desktop/harfbuzz.md
jdk-21/legal/java.desktop/jpeg.md
jdk-21/legal/java.desktop/lcms.md
jdk-21/legal/java.desktop/libpng.md
jdk-21/legal/java.desktop/mesa3d.md
jdk-21/legal/java.desktop/pipewire.md
jdk-21/legal/java.desktop/xwd.md
jdk-21/legal/java.instrument/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.instrument/ASSEMBLY_EXCEPTION
jdk-21/legal/java.instrument/LICENSE
jdk-21/legal/java.logging/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.logging/ASSEMBLY_EXCEPTION
jdk-21/legal/java.logging/LICENSE
jdk-21/legal/java.management.rmi/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.management.rmi/ASSEMBLY_EXCEPTION
jdk-21/legal/java.management.rmi/LICENSE
jdk-21/legal/java.management/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.management/ASSEMBLY_EXCEPTION
jdk-21/legal/java.management/LICENSE
jdk-21/legal/java.naming/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.naming/ASSEMBLY_EXCEPTION
jdk-21/legal/java.naming/LICENSE
jdk-21/legal/java.net.http/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.net.http/ASSEMBLY_EXCEPTION
jdk-21/legal/java.net.http/LICENSE
jdk-21/legal/java.prefs/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.prefs/ASSEMBLY_EXCEPTION
jdk-21/legal/java.prefs/LICENSE
jdk-21/legal/java.rmi/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.rmi/ASSEMBLY_EXCEPTION
jdk-21/legal/java.rmi/LICENSE
jdk-21/legal/java.scripting/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.scripting/ASSEMBLY_EXCEPTION
jdk-21/legal/java.scripting/LICENSE
jdk-21/legal/java.se/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.se/ASSEMBLY_EXCEPTION
jdk-21/legal/java.se/LICENSE
jdk-21/legal/java.security.jgss/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.security.jgss/ASSEMBLY_EXCEPTION
jdk-21/legal/java.security.jgss/LICENSE
jdk-21/legal/java.security.sasl/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.security.sasl/ASSEMBLY_EXCEPTION
jdk-21/legal/java.security.sasl/LICENSE
jdk-21/legal/java.smartcardio/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.smartcardio/ASSEMBLY_EXCEPTION
jdk-21/legal/java.smartcardio/LICENSE
jdk-21/legal/java.smartcardio/pcsclite.md
jdk-21/legal/java.sql.rowset/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.sql.rowset/ASSEMBLY_EXCEPTION
jdk-21/legal/java.sql.rowset/LICENSE
jdk-21/legal/java.sql/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.sql/ASSEMBLY_EXCEPTION
jdk-21/legal/java.sql/LICENSE
jdk-21/legal/java.transaction.xa/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.transaction.xa/ASSEMBLY_EXCEPTION
jdk-21/legal/java.transaction.xa/LICENSE
jdk-21/legal/java.xml.crypto/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.xml.crypto/ASSEMBLY_EXCEPTION
jdk-21/legal/java.xml.crypto/LICENSE
jdk-21/legal/java.xml.crypto/santuario.md
jdk-21/legal/java.xml/ADDITIONAL_LICENSE_INFO
jdk-21/legal/java.xml/ASSEMBLY_EXCEPTION
jdk-21/legal/java.xml/LICENSE
jdk-21/legal/java.xml/bcel.md
jdk-21/legal/java.xml/dom.md
jdk-21/legal/java.xml/jcup.md
jdk-21/legal/java.xml/xalan.md
jdk-21/legal/java.xml/xerces.md
jdk-21/legal/jdk.accessibility/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.accessibility/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.accessibility/LICENSE
jdk-21/legal/jdk.attach/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.attach/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.attach/LICENSE
jdk-21/legal/jdk.charsets/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.charsets/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.charsets/LICENSE
jdk-21/legal/jdk.compiler/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.compiler/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.compiler/LICENSE
jdk-21/legal/jdk.crypto.cryptoki/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.crypto.cryptoki/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.crypto.cryptoki/LICENSE
jdk-21/legal/jdk.crypto.cryptoki/pkcs11cryptotoken.md
jdk-21/legal/jdk.crypto.cryptoki/pkcs11wrapper.md
jdk-21/legal/jdk.crypto.ec/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.crypto.ec/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.crypto.ec/LICENSE
jdk-21/legal/jdk.dynalink/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.dynalink/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.dynalink/LICENSE
jdk-21/legal/jdk.dynalink/dynalink.md
jdk-21/legal/jdk.editpad/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.editpad/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.editpad/LICENSE
jdk-21/legal/jdk.hotspot.agent/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.hotspot.agent/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.hotspot.agent/LICENSE
jdk-21/legal/jdk.httpserver/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.httpserver/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.httpserver/LICENSE
jdk-21/legal/jdk.incubator.vector/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.incubator.vector/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.incubator.vector/LICENSE
jdk-21/legal/jdk.internal.ed/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.internal.ed/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.internal.ed/LICENSE
jdk-21/legal/jdk.internal.jvmstat/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.internal.jvmstat/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.internal.jvmstat/LICENSE
jdk-21/legal/jdk.internal.le/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.internal.le/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.internal.le/LICENSE
jdk-21/legal/jdk.internal.le/jline.md
jdk-21/legal/jdk.internal.opt/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.internal.opt/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.internal.opt/LICENSE
jdk-21/legal/jdk.internal.opt/jopt-simple.md
jdk-21/legal/jdk.internal.vm.ci/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.internal.vm.ci/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.internal.vm.ci/LICENSE
jdk-21/legal/jdk.internal.vm.compiler.management/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.internal.vm.compiler.management/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.internal.vm.compiler.management/LICENSE
jdk-21/legal/jdk.internal.vm.compiler/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.internal.vm.compiler/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.internal.vm.compiler/LICENSE
jdk-21/legal/jdk.jartool/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.jartool/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.jartool/LICENSE
jdk-21/legal/jdk.javadoc/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.javadoc/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.javadoc/LICENSE
jdk-21/legal/jdk.javadoc/jquery.md
jdk-21/legal/jdk.javadoc/jqueryUI.md
jdk-21/legal/jdk.jcmd/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.jcmd/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.jcmd/LICENSE
jdk-21/legal/jdk.jconsole/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.jconsole/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.jconsole/LICENSE
jdk-21/legal/jdk.jdeps/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.jdeps/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.jdeps/LICENSE
jdk-21/legal/jdk.jdi/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.jdi/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.jdi/LICENSE
jdk-21/legal/jdk.jdwp.agent/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.jdwp.agent/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.jdwp.agent/LICENSE
jdk-21/legal/jdk.jfr/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.jfr/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.jfr/LICENSE
jdk-21/legal/jdk.jlink/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.jlink/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.jlink/LICENSE
jdk-21/legal/jdk.jpackage/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.jpackage/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.jpackage/LICENSE
jdk-21/legal/jdk.jshell/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.jshell/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.jshell/LICENSE
jdk-21/legal/jdk.jsobject/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.jsobject/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.jsobject/LICENSE
jdk-21/legal/jdk.jstatd/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.jstatd/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.jstatd/LICENSE
jdk-21/legal/jdk.localedata/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.localedata/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.localedata/LICENSE
jdk-21/legal/jdk.localedata/cldr.md
jdk-21/legal/jdk.localedata/thaidict.md
jdk-21/legal/jdk.management.agent/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.management.agent/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.management.agent/LICENSE
jdk-21/legal/jdk.management.jfr/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.management.jfr/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.management.jfr/LICENSE
jdk-21/legal/jdk.management/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.management/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.management/LICENSE
jdk-21/legal/jdk.naming.dns/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.naming.dns/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.naming.dns/LICENSE
jdk-21/legal/jdk.naming.rmi/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.naming.rmi/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.naming.rmi/LICENSE
jdk-21/legal/jdk.net/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.net/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.net/LICENSE
jdk-21/legal/jdk.nio.mapmode/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.nio.mapmode/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.nio.mapmode/LICENSE
jdk-21/legal/jdk.random/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.random/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.random/LICENSE
jdk-21/legal/jdk.sctp/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.sctp/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.sctp/LICENSE
jdk-21/legal/jdk.security.auth/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.security.auth/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.security.auth/LICENSE
jdk-21/legal/jdk.security.jgss/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.security.jgss/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.security.jgss/LICENSE
jdk-21/legal/jdk.unsupported.desktop/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.unsupported.desktop/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.unsupported.desktop/LICENSE
jdk-21/legal/jdk.unsupported/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.unsupported/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.unsupported/LICENSE
jdk-21/legal/jdk.xml.dom/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.xml.dom/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.xml.dom/LICENSE
jdk-21/legal/jdk.zipfs/ADDITIONAL_LICENSE_INFO
jdk-21/legal/jdk.zipfs/ASSEMBLY_EXCEPTION
jdk-21/legal/jdk.zipfs/LICENSE
jdk-21/lib/classlist
jdk-21/lib/ct.sym
jdk-21/lib/jexec
jdk-21/lib/jfr/default.jfc
jdk-21/lib/jfr/profile.jfc
jdk-21/lib/jrt-fs.jar
jdk-21/lib/jspawnhelper
jdk-21/lib/jvm.cfg
jdk-21/lib/libattach.so
jdk-21/lib/libawt.so
jdk-21/lib/libawt_headless.so
jdk-21/lib/libawt_xawt.so
jdk-21/lib/libdt_socket.so
jdk-21/lib/libextnet.so
jdk-21/lib/libfontmanager.so
jdk-21/lib/libinstrument.so
jdk-21/lib/libj2gss.so
jdk-21/lib/libj2pcsc.so
jdk-21/lib/libj2pkcs11.so
jdk-21/lib/libjaas.so
jdk-21/lib/libjava.so
jdk-21/lib/libjavajpeg.so
jdk-21/lib/libjawt.so
jdk-21/lib/libjdwp.so
jdk-21/lib/libjimage.so
jdk-21/lib/libjli.so
jdk-21/lib/libjsig.so
jdk-21/lib/libjsound.so
jdk-21/lib/libjsvml.so
jdk-21/lib/liblcms.so
jdk-21/lib/lible.so
jdk-21/lib/libmanagement.so
jdk-21/lib/libmanagement_agent.so
jdk-21/lib/libmanagement_ext.so
jdk-21/lib/libmlib_image.so
jdk-21/lib/libnet.so
jdk-21/lib/libnio.so
jdk-21/lib/libprefs.so
jdk-21/lib/librmi.so
jdk-21/lib/libsaproc.so
jdk-21/lib/libsctp.so
jdk-21/lib/libsplashscreen.so
jdk-21/lib/libsyslookup.so
jdk-21/lib/libverify.so
jdk-21/lib/libzip.so
jdk-21/lib/modules
jdk-21/lib/psfont.properties.ja
jdk-21/lib/psfontj2d.properties
jdk-21/lib/security/blocked.certs
jdk-21/lib/security/cacerts
jdk-21/lib/security/default.policy
jdk-21/lib/security/public_suffix_list.dat
jdk-21/lib/server/classes.jsa
jdk-21/lib/server/classes_nocoops.jsa
jdk-21/lib/server/libjsig.so
jdk-21/lib/server/libjvm.so
jdk-21/lib/src.zip
jdk-21/lib/tzdb.dat
jdk-21/release
--2023-09-17 19:46:25--  https://repo1.maven.org/maven2/org/json/json/20230618/json-20230618.jar
Resolving repo1.maven.org (repo1.maven.org)... 199.232.192.209, 199.232.196.209, 2a04:4e42:4c::209, ...
Connecting to repo1.maven.org (repo1.maven.org)|199.232.192.209|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 73447 (72K) [application/java-archive]
Saving to: ‘build/libs/json.jar’

build/libs/json.jar                             100%[=======================================================================================================>]  71.73K  --.-KB/s    in 0.01s   

2023-09-17 19:46:25 (5.00 MB/s) - ‘build/libs/json.jar’ saved [73447/73447]

## Setup Process completed
To continue, run the Build Script to complete the build process.
thekintgamer@cloudshell:~/osintgram4j$ ./build.sh
You need at least the JDK version of 20. Reported Java Version is 17
To obtain the newest JDK Version, run the setup.sh with the '--force-download' argument.

**Comment by TheSg2** [comment]
it dropped me the same :b do you want me to send you the logs?

**Comment by TheCodingKitten** [comment]
if you are on debian linux then install openjdk-20-jdk (replace 20 with 21 or 22 if you want, I installed 22), that then worked fine for me

**Comment by BeChris100** [comment]
Workaround:

1. Download the latest JDK from either OpenJDK or Oracle
2. Extract the JDK .tar.gz file to the specific location of your choice
3. Set up the JAVA_HOME environment to the Root of the JDK that you just extracted into
4. Link `$JAVA_HOME/bin:$PATH` to `/etc/profile` by doing `export PATH="$JAVA_HOME/bin:$PATH"`. This will set the Java commands as primary ones.
5. Restart the Shell, or log out and log in to the Linux System to take changes.
