### ISSUE TITLE
Error, can't open osintgram4j

### ISSUE THREAD

**Issue by PoplajZ** [BeChris100/osintgram4j#11]
...............................~/osintgram4j$ osintgram4j
Usage: java [options] <mainclass> [args...]
           (to execute a class)
   or  java [options] -jar <jarfile> [args...]
           (to execute a jar file)
   or  java [options] -m <module>[/<mainclass>] [args...]
       java [options] --module <module>[/<mainclass>] [args...]
           (to execute the main class in a module)
   or  java [options] <sourcefile> [args]
           (to execute a single source-file program)

 Arguments following the main class, source file, -jar <jarfile>,
 -m or --module <module>/<mainclass> are passed as the arguments to
 main class.

 where options include:

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
    --class-path <class search path of directories and zip/jar files>
                  A : separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -p <module path>
    --module-path <module path>...
                  A : separated list of elements, each element is a file path
                  to a module or a directory containing modules. Each module is either
                  a modular JAR or an exploded-module directory.
    --upgrade-module-path <module path>...
                  A : separated list of elements, each element is a file path
                  to a module or a directory containing modules to replace
                  upgradeable modules in the runtime image. Each module is either
                  a modular JAR or an exploded-module directory.
    --add-modules <module name>[,<module name>...]
                  root modules to resolve in addition to the initial module.
                  <module name> can also be ALL-DEFAULT, ALL-SYSTEM,
                  ALL-MODULE-PATH.
    --enable-native-access <module name>[,<module name>...]
                  modules that are permitted to perform restricted native operations.
                  <module name> can also be ALL-UNNAMED.
    --list-modules
                  list observable modules and exit
    -d <module name>
    --describe-module <module name>
                  describe a module and exit
    --dry-run     create VM and load main class but do not execute main method.
                  The --dry-run option may be useful for validating the
                  command-line options such as the module system configuration.
    --validate-modules
                  validate all modules and exit
                  The --validate-modules option may be useful for finding
                  conflicts and other errors with modules on the module path.
    -D<name>=<value>
                  set a system property
    -verbose:[class|module|gc|jni]
                  enable verbose output for the given subsystem
    -version      print product version to the error stream and exit
    --version     print product version to the output stream and exit
    -showversion  print product version to the error stream and continue
    --show-version
                  print product version to the output stream and continue
    --show-module-resolution
                  show module resolution output during startup
    -? -h -help
                  print this help message to the error stream
    --help        print this help message to the output stream
    -X            print help on extra options to the error stream
    --help-extra  print help on extra options to the output stream
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:jdwp
                  see also -agentlib:jdwp=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
                  HiDPI scaled images are automatically supported and used
                  if available. The unscaled image filename, e.g. image.ext,
                  should always be passed as the argument to the -splash option.
                  The most appropriate scaled image provided will be picked up
                  automatically.
                  See the SplashScreen API documentation for more information
    @argument files
                  one or more argument files containing options
    --disable-@files
                  prevent further argument file expansion
    --enable-preview
                  allow classes to depend on preview features of this release
To specify an argument for a long option, you can use --<name>=<value> or
--<name> <value>.

**Comment by BeChris100** [comment]
Could you describe, what exactly you did to receive this?

**Comment by PoplajZ** [comment]
I did normally `cd osintgram4j` and than ran command `osintgram4j `and this appeared.

**Comment by BeChris100** [comment]
Did you also run `setup.sh` and `build.sh`, as instructed?

**Comment by PoplajZ** [comment]
Yes, I did everything as instructed and also tried reinstalling but same problem

**Comment by BeChris100** [comment]
Can you provide step-by-step on how to replicate this issue?

**Comment by PoplajZ** [comment]
I am running this on subsystem and I cloned the osintgram to my pc, than `changed directory to the osintgram`, ran the `chmod +x setup.sh build.sh` and next did the last two steps, `./setup.sh --force-download` and `./build.sh` I couldn't find out how to run the program, I tried `python3 main.py {username}`, didn't work so I tried running `osintgram4j` inside the directory and got that error. I didn't do anything else. I also tried reinstalling the program, as I said, but it didn't work either

**Comment by PoplajZ** [comment]
I have no idea how, but it worked. So I tried to use the program but I didn't know how so I ran `sessionctl {target name}` command but it told me `Session Manager is not implemented yet Requires at least one argument sessionctl: exit code 1`  Then I tried`sh` command in `./bin/osintgram4j` and after running the commnd, it told me `Process executed with PID 59` and kicked me out of  `./bin/osintgram4j`. When I tried to get back to `./bin/osintgram4j` the error appeared once again

**Comment by BeChris100** [comment]
The error, as in the Java Help Page?

With Session Manager, it is expected to happen. However, with `sh`, I'm not so sure there. Were there any errors / exceptions, when it kicked you out?

**Comment by PoplajZ** [comment]
It kicked me out right after it printed `Process executed with PID 59`

**Comment by BeChris100** [comment]
> It kicked me out right after it printed `Process executed with PID 59`

This is potentially platform-specific, meaning I am unsure, how to help. I'll try my best, though.
