### ISSUE TITLE
shows some java errors after executing command osintgram4j

### ISSUE THREAD

**Issue by karthikkl13** [BeChris100/osintgram4j#14]
hey @BeChris100 
can u tell me what the problem is??? ( btw i am new to this....)
![Screenshot_2024-05-09_03_19_20](https://github.com/BeChris100/osintgram4j/assets/149941821/3071b35b-b103-4a4b-b212-75e67b2c35f5)

**Comment by BeChris100** [comment]
Can you provide everything, from setup to building it?

**Comment by karthikkl13** [comment]
```
git clone https://github.com/BeChris100/osintgram4j && cd osintgram4j
chmod +x setup.sh build.sh
./setup.sh --force-download
./build.sh
```

after executing all this commands,
and shows build was sucessful

but after entering osintgram4j command,
its shows java error...

**Comment by BeChris100** [comment]
Right, but something within the build scripts could have failed, which I asked for the logs that you see on the Terminal.

**Comment by karthikkl13** [comment]
```
## Compiling the Commons Library
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
## Compiling the Instagram API
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
error: error reading out/libs/json.jar; zip file is empty
## Compiling the Osintgram4j API
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
error: error reading out/libs/json.jar; zip file is empty
## Compiling the Core Application
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
error: error reading out/libs/json.jar; zip file is empty
## Adding resources to the Core Application
cp: cannot create directory 'out/project/core/net/bc100dev/osintgram4j/': No such file or directory
## Making "commons.jar"
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
## Making "instagram-api.jar"
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
## Making "modapi.jar"
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
out/project/modapi/. : no such file or directory
## Making "core.jar"
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
## Building the Application Package
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
```

**Comment by BeChris100** [comment]
Either it's refusing to compile, or something else is happening. I'm not exactly sure, but I'll inspect.

I'll be looking at it, once I'm back in coding again.

In the meantime, you didn't seem to edit anything, right? I can't seem to replicate the error that you are encountering.

**Comment by karthikkl13** [comment]
Oh

**Comment by BeChris100** [comment]
Not in a bad way, but if I don't know the modifications that you have taken, then I can't help.

**Comment by BeChris100** [comment]
Can you provide the environment that you used to try running it on? Maybe I can try to do the steps that you have done on the specific Operating System that you tried installing and running on. Its specific version would also be helpful.

**Comment by karthikkl13** [comment]
I used Kali linux (2024.1 release) operating system on VMware

**Comment by BeChris100** [comment]
Identified the issue, and it's also a part of my fault here. I didn't specify the dependencies in the [README](https://github.com/BeChris100/osintgram4j/blob/master/README.md), which, eventually, you would expect to run flawlessly. I guess I was wrong.

Well, before running `setup.sh`, you also need to run:
```shell
sudo apt install tar wget cmake build-essential
```

**Comment by BeChris100** [comment]
I did some code fixes and debugging on a Kali 2024.1 VM, and figured some things out. Hope that things are fixed by now.

**Comment by karthikkl13** [comment]
Okay 
Will check
I appreciate it !

**Comment by karthikkl13** [comment]
I will check later and will tell you whether it's fixed or not

**Comment by karthikkl13** [comment]
hey 
now when i executed` ./setup.sh --force-download`
it shows this connection error:

```
Resolving repo1.maven.org (repo1.maven.org)... 146.75.116.209, 2a04:4e42:8d::209
Connecting to repo1.maven.org (repo1.maven.org)|146.75.116.209|:443... failed: Connection refused.
Connecting to repo1.maven.org (repo1.maven.org)|2a04:4e42:8d::209|:443... failed: Network is unreachable.
```

**Comment by BeChris100** [comment]
This might be the configuration on the VM you have set up. Make sure that an active connection is established.

**Comment by karthikkl13** [comment]
I did 
Still same

**Comment by BeChris100** [comment]
Did some research, and it seems like the issue might be related to the system or network settings rather than the script itself.

**Comment by karthikkl13** [comment]
Oh 
Will retry it once more later

**Comment by karthikkl13** [comment]
It works now....

**Comment by karthikkl13** [comment]
Btw
I saw all the commands 
Now, which all will work?

**Comment by BeChris100** [comment]
Go through them, and you'll know.
