### ISSUE TITLE
Can't run setup.sh

### ISSUE THREAD

**Issue by AimanRosman** [BeChris100/osintgram4j#15]
# Bug Report
When i run setup.sh it shows :
$ ./setup.sh --force-download
## Operating System State
Is Linux: true
Is OS X (macOS): false

Preparing files (JDK, Libraries)
and stop there when i continue to build.sh it tells me Some JDK tools are missing. Please re-run the setup.sh to set up the required tools.

**Comment by BeChris100** [comment]
Can you describe these following questions?

- Under what Operating System (e.g. Ubuntu 24.04, Kali Linux 2024.1) are you running this?
- How can I reproduce this error?

**Comment by BeChris100** [comment]
Identified the issue, and it's also a part of my fault here. I didn't specify the dependencies in the [README](https://github.com/BeChris100/osintgram4j/blob/master/README.md), which, eventually, you would expect to run flawlessly. I guess I was wrong.

Well, before running `setup.sh`, you also need to run:
```shell
sudo apt install tar wget cmake build-essential
```
