### ISSUE TITLE
Need to simplify its code base to work

### ISSUE THREAD

**Issue by rootlogic412** [BeChris100/osintgram4j#5]
I get an error 

## Setup Process completed
To build the project, run the Build script to complete the building process.

┌──(root㉿darthlord)-[~/osintgram4j]
└─# ./build.sh
./build.sh: line 25: [: : integer expression expected
./build.sh: line 27: [: : integer expression expected
The JDK Version could not be identified, and has returned a value of .

┌──(root㉿darthlord)-[~/osintgram4j]
└─# ./build.sh
./build.sh: line 25: [: : integer expression expected
./build.sh: line 27: [: : integer expression expected
The JDK Version could not be identified, and has returned a value of .

┌──(root㉿darthlord)-[~/osintgram4j]
└─# vi build.sh

┌──(root㉿darthlord)-[~/osintgram4j]
└─# sh -x build.sh
+ source app_ver
build.sh: 8: source: not found
+ [ -f .build-info ]
+ source .build-info
build.sh: 11: source: not found
+ [ -z  ]
+ echo Error: Some JDK tools are missing. Please re-run the setup.sh to set up the required tools.
Error: Some JDK tools are missing. Please re-run the setup.sh to set up the required tools.

**Comment by anandhakrishnan324** [comment]
I got the same

**Comment by BeChris100** [comment]
I might need to have a bit more information about this error.

- Under what Linux distribution are you running on (e.g. Kali Linux)?
- Have you run `setup.sh`, or tried to do `setup.sh --force-download` (this will download the libraries and the JDK itself)?
- From the `vi build.sh` line, what modifications have you made?
- Have you tried running under the Bash Shell?

I do want to point out that the Shell scripts are the main antagonist for the issues. With that, I'll try to provide an alternative way into building this tool, as quickly as possible.

If you have modified something that heavily breaks its functionality, do note that it won't be fixed.

**Comment by anandhakrishnan324** [comment]
./build.sh: line 25: [: : integer expression expected
./build.sh: line 27: [: : integer expression expected
The JDK Version could not be identified, and has returned a value of .
This is the error occurred when I tried to run the code then I also tried
to modify the code by adding new JDK version into the code  but it did not
work here I give you the modified code #!/bin/bash

# Load version information
source app_ver

# Check if .build-info file exists
if [ -f ".build-info" ]; then
    source .build-info

    # Check if JDK tools are available
    if [ -z "$JAR_CMD" ] || [ -z "$JAVA_CMD" ] || [ -z "$JAVAC_CMD" ] || [
-z "$JLINK_CMD" ] || [ -z "$JDEPS_CMD" ] || [ -z "$JPACKAGE_CMD" ]; then
        echo "Error: Some JDK tools are missing. Please re-run the setup.sh
to set up the required tools."
        exit 1
    fi

    # Check if JDK binaries exist and are executable
    if [ -x "$JAVA_CMD" ] && [ -x "$JAVAC_CMD" ] && [ -x "$JLINK_CMD" ] &&
[ -x "$JDEPS_CMD" ] && [ -x "$JPACKAGE_CMD" ]; then
        echo "Found JDK tools."
    else
        echo "Error: Some JDK tools are missing or not executable."
        echo "Please verify the JDK instance at \"$JAVA_DEFAULT_HOME\" and
reinstall, if necessary."
        echo "Alternatively, run the setup.sh with '--force-download' to
obtain the latest JDK version compatible with the project."
        exit 1
    fi
else
    echo "No JDK has been initialized."
    echo "To set up and initialize a JDK instance, run the setup.sh script."
    exit 1
fi

# Determine Java version
JAVA_VERSION=$("$JAVA_CMD" --version 2>&1 | grep -oP 'openjdk \K\d+' | cut
-d. -f1)

# Check if Java version meets requirements
if [ "$JAVA_VERSION" -ge 11 ]; then
    echo "Found compatible JDK version: $JAVA_VERSION"
else
    echo "Error: JDK version $JAVA_VERSION is not compatible. Please
install JDK 11 or higher."
    exit 1
fi

# Set prefix for commands requiring sudo
PREFIX=""
if [ "$EUID" -ne 0 ]; then
    if [ -n "$(command -v sudo)" ]; then
        PREFIX="sudo"
    else
        echo "Error: Root privileges are required for some operations.
Please run the script as root or using sudo."
        exit 1
    fi
fi

# ... Continue with the rest of the script as before ...

**Comment by BeChris100** [comment]
I'd suggest doing a clean download of this project, and do `setup.sh --force-download` because I have no idea, how to fix the errors. I assume that the file `.build-info` was not specified correctly.

**Comment by BeChris100** [comment]
I'll be looking to refactor, clean up and simplify some of the internal code here, which I just reopened here.

**Comment by AimanRosman** [comment]
./setup.sh --force-download
## Operating System State
Is Linux: true
Is OS X (macOS): false

Preparing files (JDK, Libraries)

i have problem with the setup.sh

**Comment by BeChris100** [comment]
> ./setup.sh --force-download
> ## Operating System State
> Is Linux: true
> Is OS X (macOS): false
> 
> Preparing files (JDK, Libraries)
> 
> i have problem with the setup.sh, after the preparing files nothing comes out and when i run build.sh it saying that jdk tools are missing
> 
> 

Fill out a new Bug Report, and I'll look into it.
