### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by rootlogic412** [BeChris100/osintgram4j#6]
After able to run osintgram4j.. No output for the commands.. What is the next step here?

(root㉿[~/osintgram4j]
└─# osintgram4j
pure virtual method called
terminate called without an active exception
Linux
The current process is running as the Root user. If you have encountered errors that may relate to not being executed without administrative privileges, you may continue, otherwise consider running processes as normal users, as it may bring unexpected damages.
As a security warning: Do not run any programs with high privileges, unless that you trust the Software that you are about to execute and you know, what you are doing.
To disable this warning message, either pass '-Sadmin_checks' or head over to the Settings file.
[root/rootlogic: osintgram4j]# help
         #&@@&#       /*%&@@@%(#    *%%%%%%%%%*   /%%(     *%#  %%%%%%%%%%%%%%
      *@@*   .@@(   .@@(      \#       .@@.       @@@@,    &@/       %@%
     (@&      (@&   &@/                #@@       *@@,@%   *@@       ,@@.
    ,@@.      &@&   ,@@@&#*           .@@        @@, #@,  &@*       %@#
    %@%      *@@         ,#@@&        (@&       *@@  ,@& ,@@       .@@,
    &@#     .@@*            @@*      .@@,       @@*   #@*@@/       %@#
    (@@.   (@@.   \\      /@@/       (@&       ,@@    .@@@@        @@,
      /%&&%//      *#&&&&&%*     ###########   ##*     /##*       /#/

sh             Runs a system interactive shell
clear          Clears the Terminal Screen
sessionctl     Session Control and Manager
setctl         Settings Control
cachectl       Cache Control
runtime        Application Runtime
appver         Application Version and Information
env            Environment Command
[root/rootlogic: osintgram4j]# sessionctl
Session Manager is not implemented yet
Requires at least one argument
sessionctl: exit code 1

**Comment by BeChris100** [comment]
Also, I might add another factor. The other commands for Instagram will only show up, once a successful connection towards a specific account has been made. Basically, what I wanted to make is Dynamic Command Loading.

**Comment by rootlogic412** [comment]
thank you for the quick response. Yes, I believed there should be a lot of adopters once you can get this working.
