### ISSUE TITLE
how to run this tool?

### ISSUE THREAD

**Issue by kamaci141** [BeChris100/osintgram4j#8]
I have successfully built it but i don't know how it works since you didn't provide any instructions. I know it is still under development but I would like to give it a try if it is able to run.

**Comment by BeChris100** [comment]
Soon. I'm finishing up Stage 1 (see `Progress.md` file). The only thing that the features are lacking are Settings and simple Session Management. After this, I'll be conducting some tests.

I promise that after the first Stage is completed, I'll add instructions, as well as successfully using the Commands provided.

**Comment by kamaci141** [comment]
ok thank you, good luck.
